blank_issues_enabled: false
contact_links:
  - name: Team Notion
    url: https://www.notion.so/Github-c3875ca9f2b946e19f32ec47ff85a719#98f71c5d5f4e43d29a696a2502f75a51
    about: 이슈 생성과 커밋컨벤션에 관한 문서
  - name: Goorm Exp page
    url: https://exp.goorm.io/education/TESIiAqKYZ88RcfzuJ/dashboard#/group/2bciMqnK11aJW8MHlY/home
    about: 25조 팀 미션 핫링크
